<script type="text/javascript" language="javascript">
//<![CDATA[
$(document).ready(function(){
	$(".content").sortuj('<?=$this->baseUrl();?>/admin/galeria/ustaw/co/galeria/');
});
//]]>
</script>
<div class="title"><h1><?=$this->controlname;?></h1></div>
<div class="row-fluid">
	<div class="span12">
		<div class="widget">
			<div class="table-header"><form action="" id="filter-form">
			</form></div>
			<table width="100%" cellspacing="0" cellpadding="0" class="adm" id="sortable">
				<thead>
					<tr>
						<th width="5%" style="text-align:center">ID</th>
						<th width="5%">Pozycja</th>
						<th width="5%">Status</th>
						<th width="65%">Nazwa</th>
						<th width="10%"></th>
                        <?php if($this->canbetranslate){?><th width="10%"></th><?php } ?>
						</tr>
				</thead>
				<tbody class="content">
					<?php foreach($this->katalog as $katalog) : ?>
					<tr id="recordsArray_<?= $this->escape($katalog->id);?>">
					<td class="center"><?= $this->escape($katalog->id);?></td>
					<td><?= $this->escape($katalog->sort);?></td>
					<td><?= status($katalog->status);?></td>
					<td><a href="<?=$this->baseUrl();?>/admin/galeria/pokaz/id/<?= $this->escape($katalog->id);?>/"><?= $this->escape($katalog->nazwa);?></a></td>
					<td class="right">
					<a href="<?=$this->baseUrl();?>/admin/galeria/pokaz/id/<?= $this->escape($katalog->id);?>/" class="actionBtn tip btnCatalog" title="Pokaż katalog" data-placement="top-right"></a>
					<a href="<?=$this->baseUrl();?>/admin/galeria/edytuj/id/<?= $this->escape($katalog->id);?>/" class="actionBtn tip btnEdit" title="Edytuj katalog" data-placement="top-right"></a>
					<a href="<?=$this->baseUrl();?>/admin/galeria/usun-katalog/id/<?= $this->escape($katalog->id);?>/" class="actionBtn tip btnDelete confirm" title="Usuń katalog" data-placement="top-right"></a>
					</td>
                    <?php if($this->canbetranslate){?>
                        <td class="right">
                            <?php foreach($this->langs as $l) { ?>
                                <a href="<?=$this->baseUrl();?>/admin/galeria/tlumaczenie/id/<?=$this->escape($katalog->id);?>/lang/<?=$this->escape($l->kod);?>/" class="actionBtn tip" title="Edytuj tłumaczenie: <?=$this->escape($l->nazwa);?>"><img src="<?=$this->baseUrl();?>/public/gfx/flags/<?=$this->escape($l->flaga);?>"></a>
                            <?php } ?>
                        </td>
                    <?php } ?>
					</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
			<div class="table-footer">
				<a href="<?=$this->baseUrl();?>/admin/galeria/nowa/" class="button greyishBtn">Nowa galeria</a>
			</div>
		</div>
	</div>
</div>