<div class="title"><h1>Ustawienia strony</h1></div>
<div class="row-fluid">
	<div class="span12">
		<ul class="nav-tabs none">
			<li class="active"><a href="<?=$this->baseUrl();?>/admin/ustawienia/"><span class="fa i-cog"></span>Główne ustawienia strony</a></li>
			<li><a href="<?=$this->baseUrl();?>/admin/ustawienia/social/"><span class="fa i-lista"></span>Portale społecznościowe</a></li>
			<li><a href="<?=$this->baseUrl();?>/admin/ustawienia/mapa/"><span class="fa i-map"></span>Kontakt</a></li>
			<li><a href="<?=$this->baseUrl();?>/admin/ustawienia/backup/"><span class="fa i-sql"></span>Kopia bazy</a></li>
			<li><a href="<?=$this->baseUrl();?>/admin/ustawienia/baner/"><span class="fa i-image"></span>Baner na start</a></li>
		</ul>
		<div class="widget">
		<div class="tab-content">
			<form id="ustawienia" name="ustawienia" enctype="application/x-www-form-urlencoded" class="mainForm" action="" method="post">
				<div class="formRow">
					<label for="adres">Adres strony</label>
					<div class="formRight tip rowInfo" data-original-title="Adres strony zaczynający się od http:// np. http://wwww.mojastrona.pl" data-placement="bottom-left"><input type="text" name="adres" id="adres" value="<?=$this->header->domena;?>" size="47" class="validate[required,custom[url]]" /></div>
				</div>
				<div class="formRow">
					<label for="mail">Adres e-mail<br /><span style="font-size:11px;color:#A8A8A8">Adresy e-mail oddzielone przecinkiem, bez spacji</span></label>
					<div class="formRight tip rowInfo" data-original-title="Adres e-mail właściciela strony" data-placement="bottom-left"><input type="text" name="mail" id="mail" value="<?=$this->header->email;?>" size="47" class="validate[required]" /></div>
				</div>
				<div class="formRow">
					<label for="autor">Autor strony<br /><span style="font-size:11px;color:#A8A8A8">Meta tag - author</span></label>
					<div class="formRight tip rowInfo" data-original-title="Autor strony" data-placement="bottom-left"><input type="text" name="autor" id="autor" value="<?=$this->header->autor;?>" size="47" class="validate[required]" /></div>
				</div>
				<div class="formRow">
					<label for="slider">Indeksowanie<br /><span style="font-size:11px;color:#A8A8A8">Meta tag - robots</span></label>
					<div class="formRight tip rowInfo" data-original-title="Ustaw sposób indeksowania strony" data-placement="bottom-left">
					<select id="robots" name="robots">
						<option value="noindex, nofollow"<?php if($this->header->robots == 'noindex, nofollow'){?> selected<?php } ?>>noindex, nofollow</option>
						<option value="index, follow"<?php if($this->header->robots == 'index, follow'){?> selected<?php } ?>>index, follow</option>
						<option value="index, nofollow"<?php if($this->header->robots == 'index, nofollow'){?> selected<?php } ?>>index, nofollow</option>
						<option value="noindex, follow"<?php if($this->header->robots == 'noindex, follow'){?> selected<?php } ?>>noindex, follow</option>
					</select>
					</div>
				</div>

				<div class="formRow">
					<label for="head">Kod w <code>&lt;head&gt;</code></label>
					<div class="formRight tip rowInfo" data-original-title="Miejsce do wklejenia kodu np. Gooogle Analytics" data-placement="bottom-left"><textarea name="head" id="head" rows="7" style="width:648px" cols="80"><?=$this->header->head;?></textarea></div>
				</div>
				<div class="formRow">
					<label for="footer">Kod przed końcem <code>&lt;body&gt;</code></label>
					<div class="formRight tip rowInfo" data-original-title="Miejsce do wklejenia kodu np. Gooogle Analytics" data-placement="bottom-left"><textarea name="footer" id="footer" rows="7" style="width:648px" cols="80"><?=$this->header->footer;?></textarea></div>
				</div>	

				<div class="formRow">
					<label for="cookies">Tekst cookies</label>
					<div class="formRight tip rowInfo" data-original-title="Tekst na pasku cookies" data-placement="bottom-left"><textarea name="cookies" id="cookies" rows="7" style="width:648px" cols="80"><?=$this->header->cookies;?></textarea></div>
				</div>
				<div class="formSubmit"><input type="submit" name="submitUstawienia" id="submit" value="Zapisz" class="greyishBtn" /></div>
			</form>
		</div>
		</div>
	</div>
</div>