<div class="title"><h1><?=$this->controlname;?> -  Ustawienia</h1></div>
<div class="row-fluid">
	<div class="span12">
		<ul class="nav-tabs none">
			<li><a href="<?=$this->baseUrl();?>/admin/slider/"><span class="fa i-image"></span>Obrazki slidera</a></li>
			<li class="active"><a href="<?=$this->baseUrl();?>/admin/slider/ustawienia/"><span class="fa i-cog"></span>Ustawienia</a></li></li>
		</ul>
		<div class="widget">
			<div class="tab-content">
				<?=$this->back ;?>
				<?=$this->info ;?>
				<?=$this->thumb ;?>
				<?=$this->form ;?>
			</div>
		</div>
	</div>
</div>