<div class="title"><h1><?=$this->controlname;?><?=$this->pagename;?></h1></div>
<div class="row-fluid">
	<div class="span12">
		<ul class="nav-tabs none">
			<li class="active"><a href="<?=$this->baseUrl();?>/admin/rodo/"><span class="fa i-lista"></span>Lista klientów</a></li>
			<li><a href="<?=$this->baseUrl();?>/admin/rodo/zgody/"><span class="fa i-lista"></span>Lista regułek</a></li>
			<li><a href="<?=$this->baseUrl();?>/admin/rodo/ustawienia/"><span class="fa i-cog"></span>Ustawienia</a></li>
		</ul>
		<div class="widget">
			<table width="100%" cellspacing="0" cellpadding="0" class="tableStatic adm" id="sortable">
				<thead>
					<tr>
					<th width="20%">Nazwa</th>
					<th width="30%">Adres e-mail</th>
					<th width="25%">Data dodania</th>
					<th width="25%">Data aktualizacji</th>
					<th width="25%">IP</th>
					<th width="10%"></th>
					</tr>
				</thead>
				<tbody class="content">
				<?php foreach($this->lista as $pozycja) : ?>
				<tr>
					<td><?=$this->escape($pozycja->nazwa);?></td>
					<td><?=$this->escape($pozycja->mail);?></td>
					<td><?=$this->escape($pozycja->data_dodania);?></td>
					<td><?=$this->escape($pozycja->data_aktualizacji);?></td>
					<td><?=$this->escape($pozycja->ip);?></td>
					<td class="right"><a href="<?=$this->baseUrl();?>/admin/rodo/pokaz/id/<?=$this->escape($pozycja->id);?>/" class="actionBtn tip btnCatalog" title="Pokaż wpis"></a></td>
				</tr>
				<?php endforeach; ?>
				</tbody>
			</table>
		</div>
	</div>
</div>