<div class="title"><h1><?=$this->controlname;?><?=$this->pagename;?></h1></div>
<div class="row-fluid">
	<div class="span12">
		<ul class="nav-tabs none">
			<li><a href="<?=$this->baseUrl();?>/admin/rodo/"><span class="fa i-lista"></span>Lista klientów</a></li>
			<li class="active"><a href="<?=$this->baseUrl();?>/admin/rodo/zgody/"><span class="fa i-lista"></span>Lista regułek</a></li>
			<li><a href="<?=$this->baseUrl();?>/admin/rodo/ustawienia/"><span class="fa i-cog"></span>Ustawienia</a></li>
		</ul>
		<div class="widget">
			<table width="100%" cellspacing="0" cellpadding="0" class="tableStatic adm" id="sortable">
				<thead>
					<tr>
					<th width="45%">Nazwa</th>
					<th width="15%">Data dodania</th>
					<th width="15%">Data edycji</th>
					<th width="5%" class="center">Termin</th>
					<th width="5%" class="center">Wymagane</th>
					<th width="5%" class="center">Status</th>
					<th width="10"></th>
					</tr>
				</thead>
				<tbody class="content">
				<?php foreach($this->lista as $pozycja) : ?>
				<tr id="recordsArray_<?=$this->escape($pozycja->id);?>">
					<td><?=$this->escape($pozycja->nazwa);?></td>
					<td><?=date('d-m-Y - H:i:s', $pozycja->data_utworzenia);?></td>
					<td><?=date('d-m-Y - H:i:s', $pozycja->data_edycji);?></td>
					<td class="center"><?=$this->escape($pozycja->termin);?></td>
					<td><?=status($pozycja->wymagane);?></td>
					<td><?=status($pozycja->status);?></td>
					<td class="right">
						<a href="<?=$this->baseUrl();?>/admin/rodo/edytuj-regulka/id/<?=$this->escape($pozycja->id);?>/" class="actionBtn tip btnEdit" title="Edytuj wpis"></a>
						<a href="<?=$this->baseUrl();?>/admin/rodo/usun-regulka/id/<?=$this->escape($pozycja->id);?>/" class="actionBtn tip btnDelete confirm" title="Usuń wpis"></a>
					</td>
				</tr>
				<?php endforeach; ?>
				</tbody>
			</table>
			<div class="table-footer">
				<a href="<?=$this->baseUrl();?>/admin/rodo/nowa-regulka/" class="button greyishBtn">Dodaj regułkę</a>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript" language="javascript">
//<![CDATA[
$(document).ready(function(){
	$("#sortable tbody.content").sortuj('<?=$this->baseUrl();?>/admin/rodo/ustaw/');
});
//]]>
</script>