<div class="container">
    <?php foreach($this->katalog as $int => $k) { ?>
        <div class="<?php echo fmod($int, 2) ? 'row mt-5' : 'row flex-row-reverse' ?>">
            <div class="col-6 d-flex align-items-center">
                <div class="gallery-name text-center">
                    <h2><a href="<?=$this->url(array(
                            'language' => $this->lang,
                            'slug'=> $k->slug
                        ), 'gallery-show');?>"><?php echo (isset($k->nazwa)) ? $k->nazwa : json_decode($k->json)->nazwa;?></a></h2>
                    <a href="<?=$this->url(array(
                        'language' => $this->lang,
                        'slug'=> $k->slug
                    ), 'gallery-show');?>" class="bttn justify-content-center"><?=$this->translate('tl_zobacz_galerie');?></a>
                </div>
            </div>
            <div class="col-6">
                <a href="<?=$this->url(array(
                    'language' => $this->lang,
                    'slug'=> $k->slug
                ), 'gallery-show');?>">
                <img src="<?=$this->filesUrl(); ?>/galeria/catalog/<?=$k->plik;?>" alt="<?php echo (isset($k->nazwa)) ? $k->nazwa : json_decode($k->json)->nazwa;?>">
                </a>
            </div>
        </div>
    <?php } ?>
</div>