<div class="title"><h1><?=$this->controlname;?></h1></div>
<div class="row-fluid">
    <div class="span12">
        <div class="widget">
            <table width="100%" cellspacing="0" cellpadding="0" class="tableStatic adm" id="sortable">
                <thead>
                <tr>
                    <th width="60%">Nazwa</th>
                    <th width="20%">Ikonka</th>
                    <th width="10%"></th>
                    <?php if($this->canbetranslate){?><th width="10%"></th><?php } ?>
                </tr>
                </thead>
                <tbody class="content">
                <?php foreach($this->lista as $pozycja) : ?>
                    <tr id="recordsArray_<?=$this->escape($pozycja->id);?>">
                        <td><?=$pozycja->nazwa?></td>
                        <td><?php if($pozycja->plik){?><img src="<?=$this->baseUrl();?>/files/images/<?=$this->escape($pozycja->plik);?>" alt=""><?php } ?></td>
                        <td class="right">
                            <a href="<?=$this->baseUrl();?>/admin/atuty/edit/id/<?=$this->escape($pozycja->id);?>/" class="actionBtn tip btnEdit" title="Edytuj wpis"></a>
                            <a href="<?=$this->baseUrl();?>/admin/atuty/delete/id/<?=$this->escape($pozycja->id);?>/" class="actionBtn tip btnDelete confirm" title="Usuń"></a>
                        </td>
                        <?php if($this->canbetranslate){?>
                            <td class="right">
                                <?php foreach($this->langs as $l) { ?>
                                    <a href="<?=$this->baseUrl();?>/admin/atuty/tlumaczenie/id/<?=$this->escape($pozycja->id);?>/lang/<?=$this->escape($l->kod);?>/" class="actionBtn tip" title="Edytuj tłumaczenie: <?=$this->escape($l->nazwa);?>"><img src="<?=$this->baseUrl();?>/public/gfx/flags/<?=$this->escape($l->flaga);?>"></a>
                                <?php } ?>
                            </td>
                        <?php } ?>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
            <div class="table-footer">
                <a href="<?=$this->baseUrl();?>/admin/atuty/add/" class="button greyishBtn">Dodaj atut</a>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    //<![CDATA[
    $(document).ready(function(){
        $("#sortable tbody.content").sortuj('<?=$this->baseUrl();?>/admin/atuty/sort/');
    });
    //]]>
</script>