<ul id="menu" class="none">
    <li<?php if($this->control == 'ustawienia'){ echo ' class="active"';} ?>><a href="<?=$this->baseUrl();?>/admin/ustawienia/"><span class="fa m-ustawienia"></span>Ustawienia</a></li>
    <li<?php if($this->control == 'tlumaczenie'){ echo ' class="active"';} ?>><a href="<?=$this->baseUrl();?>/admin/tlumaczenie/"><span class="fa m-tlumaczenie"></span>Tłumaczenie</a></li>
    <li<?php if($this->control == 'rodo'){ echo ' class="active"';} ?>><a href="<?=$this->baseUrl();?>/admin/rodo/"><span class="fa m-rodo"></span>RODO</a></li>
    <li<?php if($this->control == 'uzytkownicy'){ echo ' class="active"';} ?>><a href="<?=$this->baseUrl();?>/admin/uzytkownicy/"><span class="fa m-uzytkownicy"></span>Użytkownicy</a></li>
    <li<?php if($this->control == 'blokowanie'){ echo ' class="active"';} ?>><a href="<?=$this->baseUrl();?>/admin/blokowanie/"><span class="fa m-blokowanie"></span>Blokada dostępu</a></li>
    <li<?php if($this->control == 'slider'){ echo ' class="active"';} ?>><a href="<?=$this->baseUrl();?>/admin/slider/"><span class="fa m-slider"></span>Slider</a></li>
    <li<?php if($this->control == 'atuty'){ echo ' class="active"';} ?>><a href="<?=$this->baseUrl();?>/admin/atuty/"><span class="fa m-boksy"></span>Atuty</a></li>
    <li<?php if($this->control == 'strony'){ echo ' class="active"';} ?>><a href="<?=$this->baseUrl();?>/admin/strony/"><span class="fa m-strony"></span>Strony</a></li>
    <li<?php if($this->control == 'oferta'){ echo ' class="active"';} ?>><a href="<?=$this->baseUrl();?>/admin/oferta/"><span class="fa m-book"></span>Oferta</a></li>
    <li<?php if($this->control == 'galeria'){ echo ' class="active"';} ?>><a href="<?=$this->baseUrl();?>/admin/galeria/"><span class="fa m-galeria"></span>Galeria</a></li>
</ul>