<footer>
	<div id="footer">
		<div class="container">
			<div class="row">
                <div class="col-3">
                    <div id="logo">
                        <a href="<?=$this->baseUrl();?>/<?= ($this->lang == 'pl') ? '' : 'en/';?>">
                            <img src="<?=$this->gfxUrl();?>/template/logo.png" alt="<?= $this->header->nazwa; ?>">
                        </a>
                    </div>
                </div>
                <div class="col-3 d-flex align-items-center">
                    <div class="footer-text">
                        <p>Kaczmarek Paweł</p>
                        <p>62-200 Gniezno</p>
                        <p>ul. Aleja Szósta 3</p>
                    </div>
                </div>
                <div class="col-3 d-flex align-items-center">
                    <div class="footer-text">
                        <p>T: <a href="tel:607615711">607615711</a></p>
                        <p>E: <a href="mailto:kaczmarek@kaczmarekkowal.pl">kaczmarek@kaczmarekkowal.pl</a></p>
                    </div>
                </div>
                <div class="col-3 d-flex align-items-center justify-content-end">
                    <a href="#" id="top"><i class="las la-angle-double-up"></i></a>
                </div>
			</div>
		</div>
	</div>
</footer>

<div id="cookies"><p><a href="#" class="closecookies gradient">Zamknij</a><?= $this->header->cookies; ?></p></div>

<!-- Google fonts -->
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600,700&display=swap" rel="stylesheet">
