<header class="clearfix">
	<div class="header-holder">
		<div id="header">
			<div class="container-fluid p-0">
				<div class="row no-gutters">
					<div class="col-3">
						<div id="logo">
                            <a href="<?=$this->baseUrl();?>/<?= ($this->lang == 'pl') ? '' : 'en/';?>">
                                <img src="<?=$this->gfxUrl();?>/template/logo.png" alt="<?= $this->header->nazwa; ?>">
                            </a>
                        </div>
					</div>
					<div class="col-9">
                        <nav class="navbar">
                            <ul class="mainmenu list-unstyled text-right mb-0">
                                <li><a href="<?=$this->url(array(), 'about');?>">O firmie</a></li>
                                <li><a href="<?=$this->baseUrl();?>/oferta/">Oferta</a></li>
                                <li><a href="<?=$this->url(array(), 'gallery');?>">Galeria</a></li>
                                <li><a href="<?=$this->url(array(), 'contact');?>">Kontakt</a></li>
                                <?php $this->menu->get_menu_html(); ?>
                            </ul>
                            <div id="headercta">
                                <a href="tel:<?=$this->header->kontakt_telefon;?>">ZADZWOŃ DO NAS<br><strong><?=$this->header->kontakt_telefon;?></strong></a>
                            </div>
                        </nav>
					</div>
				</div>
			</div>
		</div>
	</div>
</header>
<div id="megamenu-opacity"></div>
<aside>
    <ul>
        <?php if($this->header->fb) {?><li><a rel="nofollow" target="_blank" class="Facebook" href="<?= $this->header->fb; ?>"><span>Facebook</span></a></li><?php } ?>
    </ul>
</aside>