<!doctype html>
<html lang="pl">
<head>
    <meta charset="utf-8">
    <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge"><![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
	
<?php if($this->seo_tytul) {?>
	<title><?= $this->seo_tytul; ?></title>
<?php } else { ?>
	<title><?= $this->main_meta_tytul; ?><?= $this->strona_tytul; ?></title>
<?php } ?>
<?php if($this->seo_opis) {?>
	<meta name="description" content="<?= $this->seo_opis; ?>">
<?php } else { ?>
	<meta name="description" content="<?= $this->main_meta_opis; ?>">
<?php } ?>
<?php if($this->seo_slowa) {?>
	<meta name="keywords" content="<?= $this->seo_slowa; ?>">
<?php } else { ?>
	<meta name="keywords" content="<?= $this->main_meta_slowa; ?>">
<?php } ?>
<?php if($this->header->autor){?>
	<meta name="author" content="<?= $this->header->autor; ?>">
<?php } ?>
<?php if($this->nofollow == 1) {?>
	<meta name="robots" content="noindex, nofollow">
	<!-- Wyłączone z akcji -->
<?php } else { ?>
	<meta name="robots" content="<?= $this->header->robots; ?>">
<?php } ?>
<?php if($this->canonical) {?>
	<meta name="canonical" content="<?=$this->canonical;?>">
<?php } ?>

<?php if($this->share == 1) {?>
	<meta property="og:title" content="<?=$this->share_tytul;?>">
	<meta property="og:image" content="<?=$this->share_image;?>">
	<meta property="og:description" content="<?=str_replace('"', '', $this->share_desc);?>">
	<meta property="og:type" content="article">
	<meta property="og:image:width" content="600">
	<meta property="og:image:height" content="315">
	<meta property="og:url" content="<?=$this->share_url;?>">
<?php } ?>

    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">

    <!-- Wylaczenie numeru tel. -->
	<meta name="format-detection" content="telephone=no">
	
	<!-- Prefetch -->
	<link rel="dns-prefetch" href="//maps.google.com">
	<link rel="dns-prefetch" href="//fonts.googleapis.com">

    <!-- Styles -->
    <link rel="stylesheet" href="<?=$this->cssUrl();?>/bootstrap.css">
    <link rel="stylesheet" href="<?=$this->cssUrl();?>/styles.css?data=<?=date('is');?>">
	
	<!-- jQuery -->
    <script src="<?=$this->jsUrl(); ?>/jquery.js" charset="utf-8"></script>
	<script src="<?=$this->jsUrl(); ?>/bootstrap.min.js" charset="utf-8"></script>
    <script src="<?=$this->jsUrl(); ?>/main.js" charset="utf-8"></script>
	
	<?php echo $this->header->head; ?>

	<?php //getRecaptchaBody(); ?>
</head>
<body class="subpage<?php if(Zend_Auth::getInstance()->hasIdentity() && $this->editinline){?> is-admin<?php } ?>">
	<?=$this->render('header.phtml');?>

    <?php if(!$this->hidepageheader) { ?>
    <?=$this->render('pageheader.phtml');?>
    <?php } ?>

    <div id="page" class="<?php if($this->nobottom){?> nobottom <?php } ?><?php if($this->notop){?> notop <?php } ?><?=$this->pageclass;?> <?php if(isset($this->strona->tag)){?><?=$this->strona->tag;?>-pageheader<?php } ?>">
        <div class="page-content">
            <?= $this->layout()->content; ?>
        </div>
    </div>

	<div class="page-footer">
	<?=$this->render('footer.phtml');?>
	</div>

    <?php if($this->validation) { ?>
        <script src="<?=$this->jsUrl(); ?>/validation.js" charset="utf-8"></script>
        <script src="<?=$this->jsUrl(); ?>/pl.js" charset="utf-8"></script>
    <?php } ?>

	<script type="text/javascript">
	$(document).ready(function(){
        <?php if($this->validation) { ?>
        $(".validateForm").validationEngine({
            validateNonVisibleFields: true,
            updatePromptsPosition:true,
            promptPosition : "topRight:-128px"
        });
        <?php } ?>
	});
	$(window).load(function() {
        <?php if($this->message == 1) {?>
        const aboveHeight = $('#header').outerHeight();
        $('html, body').stop().animate({
            scrollTop: $('#formalert').offset().top-aboveHeight
        }, 1500, 'easeInOutExpo');
        <?php } ?>
	});
	</script>

	<?= $this->header->footer; ?>
</body>
</html>